server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  session:
    store-type: none
lazydsr:
  security:
    browser:
      loginType: JSON
#lazydsr:
#  security:
#    browser:
#      loginPage: /demo-login.html
#security:
#  basic:
#    enabled: false